apiVersion: v1
kind: Service
metadata:
  name: iris-flask-app
spec:
  type: ClusterIP  # Change this to ClusterIP
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
  selector:
    app: iris-flask-app
